# Generated by Django 3.1.6 on 2021-02-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='caption',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='meme',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
